name: flutter_time_ago
description: A new Flutter package to format datetime or milliseconds in seconds ago, minutes ago, hours ago, days ago and from now.
version: 0.0.2
homepage: https://github.com/wesleytoshio/flutter_time_ago

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  timer_builder: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
